FROM node:20.13.0-alpine3.18

WORKDIR /app
COPY /package*.json ./
COPY /package-lock.json ./
#BUILD IT BEFORE RUNNING THE COMPOSE
COPY /build ./build

EXPOSE 80
CMD ["npx","serve","-s","build","-p","80"]
