version: '3.3'
services:
  back-end:
    build:
      context:
        server
      dockerfile:
        Dockerfile
    ports:
      - "4000:4000"
    environment:
      DB_PORT: dbport
      DB_HOST: dbhost
      DB_USER: dbuser
      DB_PASSWORD: dbpass
      DB: dbname
  front-end:
    build:
      context:
        client
      dockerfile:
        Dockerfile.prod
    ports:
      - "80:80"