version: '3.3'
services:
  front-end:
    build:
      context:
        client
      dockerfile:
        Dockerfile.prod
    ports:
      - "3000:3000"
  back-end:
    build:
      context:
        server
      dockerfile:
        Dockerfile
    ports:
      - "4000:4000"