name: Deploy API

on:
  push:
    branches: [main]
    paths: [server/**]

jobs:
  deploy:
    environment: Prod
    runs-on: ubuntu-latest
    steps:
    - 
      uses: actions/checkout@v3
    - 
      name: Build the Docker Image
      run: docker build -f Dockerfile -t john4064/project-gen:backend
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build & Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: john4064/project-gen:backend
