name: Deploy API

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'server/**'
      
jobs:
  build:
    environment: Prod
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout Actions
      uses: actions/checkout@v4
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Docker Build Backend
      run: |
        docker build -f server/Dockerfile -t john4064/project-gen:backend ./server
    - 
      name: Docker Push Backend
      run: |
        docker push john4064/project-gen:backend
