name: Deploy API

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      #env:
        #DOCKER_USER: ${{ secrets.DOCKERHUB_USER }}   
        #DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build Backend
      run: |
        docker build -f Dockerfile -t john4064/project-gen:backend
    - name: docker push
      run: |
        docker push john4064/project-gen:backend
